module.exports = Object.freeze({
    HASH_ITER: 300000,
    HASH_SALT_LEN: 32,
    HASH_LEN: 32,
    HASH_ALGO: 'sha256',
    legalStripParams: [
        'brightness',
        'ballcount',
        'ballFade',
        'ballMirrored',
        'ballSpeedKnob',
        'cometDelay',
        'cometDeltaHue',
        'cometFadeAmt',
        'cometSize',
        'currentEffect',
        'fireCooling',
        'fireMirrored',
        'firePalette',
        'fireReversed',
        'fireSparkHeight',
        'fireSparking',
        'fireSparks',
        'marqueeColor',
        'marqueeDelay',
        'marqueeDeltaScroll',
        'marqueeNumLeds',
        'rainbowSpeed',
        'rainbowDeltaHue',
        'solidColor',
        'twinkleCount',
        'twinkleDelay',
        'twinkleFadeFactor'
        ]
});
